// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyIdf_aR3ic2qhA4mnGfowGFU_2jrzaNI',
    appId: '1:447425667347:web:c70052ad80c08b2f497ae6',
    messagingSenderId: '447425667347',
    projectId: 'controle-financeiro-4394a',
    authDomain: 'controle-financeiro-4394a.firebaseapp.com',
    storageBucket: 'controle-financeiro-4394a.firebasestorage.app',
    measurementId: 'G-GCWE0J2NMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX3ScdzMsj7DFvVdFLJtZ2aNPSz8CRnzY',
    appId: '1:447425667347:android:627876578b821482497ae6',
    messagingSenderId: '447425667347',
    projectId: 'controle-financeiro-4394a',
    storageBucket: 'controle-financeiro-4394a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHtz7PNcpJTMtvISNcSLXZfVbEJzMeo18',
    appId: '1:447425667347:ios:e54423ac8f5034cd497ae6',
    messagingSenderId: '447425667347',
    projectId: 'controle-financeiro-4394a',
    storageBucket: 'controle-financeiro-4394a.firebasestorage.app',
    iosBundleId: 'com.example.riverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHtz7PNcpJTMtvISNcSLXZfVbEJzMeo18',
    appId: '1:447425667347:ios:e54423ac8f5034cd497ae6',
    messagingSenderId: '447425667347',
    projectId: 'controle-financeiro-4394a',
    storageBucket: 'controle-financeiro-4394a.firebasestorage.app',
    iosBundleId: 'com.example.riverpod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyIdf_aR3ic2qhA4mnGfowGFU_2jrzaNI',
    appId: '1:447425667347:web:f27c799b1d540d84497ae6',
    messagingSenderId: '447425667347',
    projectId: 'controle-financeiro-4394a',
    authDomain: 'controle-financeiro-4394a.firebaseapp.com',
    storageBucket: 'controle-financeiro-4394a.firebasestorage.app',
    measurementId: 'G-6Z9V1EYM1H',
  );
}
